timocov/dts-bundle-generator

README.md
src/bundle-generator.ts
src/cli.ts

Fixes #1 
According https://github.com/timocov/dts-bundle-generator/issues/1#issuecomment-334972526 this PR uses second approach (import type from `main` file of the library) to solve the problem.

Added emitting `import` directive for white-listed libraries

---

src/bundle-generator.ts

Fixed: JSDoc of exported item does not present in output

---

README.md
src/bundle-generator.ts
src/cli.ts
src/node-modules-helpers.ts

Fixes #3 
- Added `--external-types` cli option

 Added generating triple-slash reference directive for libraries from @types

---

README.md
src/bundle-generator.ts
src/cli.ts
src/node-modules-helpers.ts

Added possibility to import all external libraries (except inlined)

---

src/bundle-generator.ts
src/types-usage-evaluator.ts
tests/test-cases/import-compound-type-from-npm-cause-unnecessary-import/config.ts
tests/test-cases/import-compound-type-from-npm-cause-unnecessary-import/input.ts
tests/test-cases/import-compound-type-from-npm-cause-unnecessary-import/output.d.ts
tests/test-cases/node_modules/fake-package/index.ts

Fixed: Some imports makes adding unnecessary imports

---

src/bundle-generator.ts
src/typescript-helpers.ts
tests/test-cases/handle-export-eq-from-npm/config.ts
tests/test-cases/handle-export-eq-from-npm/input.ts
tests/test-cases/handle-export-eq-from-npm/output.d.ts
tests/test-cases/node_modules/package-with-export-eq/index.ts

 Added handling `export =` with namespace in imported packages

---

src/bundle-generator.ts
tests/test-cases/re-export-from-importable-module/config.ts
tests/test-cases/re-export-from-importable-module/input.ts
tests/test-cases/re-export-from-importable-module/interface.ts
tests/test-cases/re-export-from-importable-module/output.d.ts

Added handling reexports from entry file

---

README.md
src/bin/dts-bundle-generator.ts
src/bundle-generator.ts
src/compile-dts.ts

- Added experimental `--disable-symlinks-following` cli option
- Increased CLI help output max width up to 100 (instead of 80)
Fixes #39

Added possibility to disable resolving symlinks to original path

---

src/bundle-generator.ts
tests/test-cases/import-variables/config.ts
tests/test-cases/import-variables/input.ts
tests/test-cases/import-variables/output.d.ts
tests/test-cases/node_modules/package-with-typings/index.d.ts

Fix importing variables

---

src/generate-output.ts
tests/test-cases/inline-from-deps/input.ts
tests/test-cases/inline-from-deps/output.d.ts
tests/test-cases/node_modules/fake-package/some-class.d.ts

Add `declare` keyword to ClassDeclaration nodes if it is not presented yet

---

src/compile-dts.ts

Added warning about non-declaration files in the compilation

---

src/bundle-generator.ts
src/helpers/typescript.ts
tests/test-cases/export-eq-from-entry/config.ts
tests/test-cases/export-eq-from-entry/input.ts
tests/test-cases/export-eq-from-entry/output.d.ts
tests/test-cases/export-eq-from-entry/some-class.ts

Added checking that node is exported in CommonJS or ES6 style

---

README.md
src/bundle-generator.ts
src/helpers/typescript.ts
tests/test-cases/default-export-of-default-export/class.ts
tests/test-cases/default-export-of-default-export/config.ts
tests/test-cases/default-export-of-default-export/input.ts
tests/test-cases/default-export-of-default-export/output.d.ts
tests/test-cases/export-default-just-declared-class-from-entry/config.ts
tests/test-cases/export-default-just-declared-class-from-entry/input.ts
tests/test-cases/export-default-just-declared-class-from-entry/output.d.ts

Fixes #17
(the branch from #60)

Added checking that node is exported in `export default` ES6 style

---

README.md
src/bin/dts-bundle-generator.ts
src/bundle-generator.ts
src/compile-dts.ts
src/config-file/README.md
src/config-file/check-schema-match.ts
src/config-file/load-config-file.ts
src/get-compiler-options.ts
src/helpers/fix-path.ts
src/helpers/get-absolute-path.ts
src/module-info.ts
tests/functional-test-cases.ts
tests/test-case-sample/config.ts
tests/test-cases/dont-inline-declare-global/config.ts
tests/test-cases/external-types/config.ts
tests/test-cases/handle-export-eq-from-npm/config.ts
tests/test-cases/import-from-deps/config.ts
tests/test-cases/import-from-types/config.ts
tests/test-cases/inline-declare-global/config.ts
tests/test-cases/inline-from-deps/config.ts
tests/test-cases/sort-nodes/config.ts
tests/test-cases/test-case-config.ts
tests/test-cases/umd-module-name/config.ts
tests/unittests/check-schema-match.spec.ts

Multiple entries

---

.dev-deps/package.json
dts-config.js
package.json
src/config-file/README.md
src/config-file/load-config-file.ts
tsconfig.base.json

Own dts files in the package

---

.gitignore
src/bundle-generator.ts
src/types-usage-evaluator.ts
tests/functional-test-cases.ts
tests/test-cases/import-package-with-declaration-merging-with-default-lib/config.ts
tests/test-cases/import-package-with-declaration-merging-with-default-lib/input.ts
tests/test-cases/import-package-with-declaration-merging-with-default-lib/output.d.ts
tests/test-cases/node_modules/@types/fake-types-lib-3/global.d.ts
tests/test-cases/node_modules/@types/fake-types-lib-3/index.d.ts

Do not import nodes from the default library

---

src/generate-output.ts
tests/test-cases/sort-nodes/input.ts
tests/test-cases/sort-nodes/output.d.ts

Do not use jsdoc while sorting nodes

---

src/compile-dts.ts
tests/e2e/tsconfig.json

Set declaration compiler option to true while generating declarations

---

src/bundle-generator.ts
src/helpers/typescript.ts
src/types-usage-evaluator.ts
tests/e2e/test-cases/import-from-interface-with-export-eq/config.ts
tests/e2e/test-cases/import-from-interface-with-export-eq/input.ts
tests/e2e/test-cases/import-from-interface-with-export-eq/output.d.ts
tests/e2e/test-cases/node_modules/@types/commander/index.d.ts

Added handling transient symbols

---

README.md
src/bundle-generator.ts
src/generate-output.ts
src/helpers/typescript.ts
tests/e2e/test-cases/default-export-of-default-export/input.ts
tests/e2e/test-cases/default-export-of-default-export/output.d.ts
tests/e2e/test-cases/re-export-from-importable-module/class.ts
tests/e2e/test-cases/re-export-from-importable-module/input.ts
tests/e2e/test-cases/re-export-from-importable-module/interface.ts
tests/e2e/test-cases/re-export-from-importable-module/output.d.ts
tests/e2e/test-cases/re-export-from-importable-module/variables.ts

Added handling re-export with renamings

---

src/bundle-generator.ts
tests/e2e/test-cases/import-from-types-cause-reference-types/config.ts
tests/e2e/test-cases/import-from-types-cause-reference-types/extended-data.ts
tests/e2e/test-cases/import-from-types-cause-reference-types/input.ts
tests/e2e/test-cases/import-from-types-cause-reference-types/output.d.ts
tests/e2e/test-cases/import-from-types-cause-reference-types/tsconfig.json
tests/e2e/test-cases/import-from-types/output.d.ts
tests/e2e/test-cases/node_modules/@types/fake-types-lib-2/index.d.ts

Added referencing to types if a statement is used from types and it's allowed by config

---

src/bundle-generator.ts
src/helpers/typescript.ts
tests/e2e/test-cases/re-export-default-export-with-same-name/class-names/class-names.ts
tests/e2e/test-cases/re-export-default-export-with-same-name/class-names/index.ts
tests/e2e/test-cases/re-export-default-export-with-same-name/config.ts
tests/e2e/test-cases/re-export-default-export-with-same-name/input.ts
tests/e2e/test-cases/re-export-default-export-with-same-name/is-promise/index.ts
tests/e2e/test-cases/re-export-default-export-with-same-name/is-promise/is-promise.ts
tests/e2e/test-cases/re-export-default-export-with-same-name/output.d.ts
tests/e2e/test-cases/re-export-from-importable-module/output.d.ts

Fixed incorrect handling re-export default export with setting a name to the original one

---

src/helpers/typescript.ts
src/types-usage-evaluator.ts
tests/e2e/test-cases/labelled-tuples/config.ts
tests/e2e/test-cases/labelled-tuples/input.ts
tests/e2e/test-cases/labelled-tuples/output.d.ts

Fixed error with labelled tuples

---

src/bundle-generator.ts
src/helpers/typescript.ts
src/types-usage-evaluator.ts
tests/e2e/test-cases/extend-other-module-complex/config.ts
tests/e2e/test-cases/extend-other-module-complex/extendable-module.ts
tests/e2e/test-cases/extend-other-module-complex/extender.ts
tests/e2e/test-cases/extend-other-module-complex/input.ts
tests/e2e/test-cases/extend-other-module-complex/internal-extender/extender.d.ts
tests/e2e/test-cases/extend-other-module-complex/output.d.ts

related to: https://github.com/timocov/dts-bundle-generator/issues/148

add failing test case for demonstration purposes

---

src/bundle-generator.ts
src/generate-output.ts
tests/e2e/test-cases/import()-type/config.ts
tests/e2e/test-cases/import()-type/custom-type.d.ts
tests/e2e/test-cases/import()-type/input.ts
tests/e2e/test-cases/import()-type/my-type.d.ts
tests/e2e/test-cases/import()-type/output.d.ts

Fixed wrong typings when import() is used for types from local modules

---

src/bundle-generator.ts
tests/e2e/test-cases/re-export-from-paths-module/config.ts
tests/e2e/test-cases/re-export-from-paths-module/input.ts
tests/e2e/test-cases/re-export-from-paths-module/module.ts
tests/e2e/test-cases/re-export-from-paths-module/output.d.ts
tests/e2e/test-cases/re-export-from-paths-module/tsconfig.json

Added handling `paths` compiler option to resolve re-exports from an entry point

---

src/bundle-generator.ts
tests/e2e/test-cases/import()-type/config.ts
tests/e2e/test-cases/import()-type/my-type.d.ts
tests/e2e/test-cases/import()-type/output.d.ts

Fixed incorrect handling inlining import() statements

---

src/bundle-generator.ts
tests/e2e/test-cases/import-eq-with-interop/config.ts
tests/e2e/test-cases/import-eq-with-interop/export-eq.ts
tests/e2e/test-cases/import-eq-with-interop/input.ts
tests/e2e/test-cases/import-eq-with-interop/output.d.ts
tests/e2e/test-cases/import-eq-with-interop/tsconfig.json
tests/e2e/test-cases/import-with-different-names/config.ts
tests/e2e/test-cases/import-with-different-names/input.ts
tests/e2e/test-cases/import-with-different-names/other-module.ts
tests/e2e/test-cases/import-with-different-names/output.d.ts
tests/e2e/test-cases/import-with-different-names/tsconfig.json

Fixed handling `import = require` syntax and "import default"

---

src/compile-dts.ts
tests/e2e/all-test-cases.ts
tests/e2e/test-cases/cts-extension/config.ts
tests/e2e/test-cases/cts-extension/decl.d.cts
tests/e2e/test-cases/cts-extension/file.cts
tests/e2e/test-cases/cts-extension/input.cts
tests/e2e/test-cases/cts-extension/output.d.ts
tests/e2e/test-cases/mts-extension/config.ts
tests/e2e/test-cases/mts-extension/decl.d.mts
tests/e2e/test-cases/mts-extension/file.mts
tests/e2e/test-cases/mts-extension/input.mts
tests/e2e/test-cases/mts-extension/output.d.ts

Added support for the `.mts` and `.cts` extensions

---

src/helpers/typescript.ts
tests/e2e/test-cases/underscore-in-name/config.ts
tests/e2e/test-cases/underscore-in-name/func.ts
tests/e2e/test-cases/underscore-in-name/input.ts
tests/e2e/test-cases/underscore-in-name/output.d.ts

Fixed handling double-underscored names

---

src/bundle-generator.ts
src/helpers/typescript.ts
tests/e2e/test-cases/node_modules/package-with-re-exports/content.d.ts
tests/e2e/test-cases/node_modules/package-with-re-exports/index.d.ts
tests/e2e/test-cases/re-export-in-node_modules/config.ts
tests/e2e/test-cases/re-export-in-node_modules/input.ts
tests/e2e/test-cases/re-export-in-node_modules/output.d.ts

Fixed accidentally inlining export statements while inlining a library with namespaced imports/exports

---

src/bundle-generator.ts
src/types-usage-evaluator.ts
tests/e2e/test-cases/export-wrapped-with-namespace/output.d.ts
tests/e2e/test-cases/import-star-from-local-module/config.ts
tests/e2e/test-cases/import-star-from-local-module/func.ts
tests/e2e/test-cases/import-star-from-local-module/index.spec.js
tests/e2e/test-cases/import-star-from-local-module/input.ts
tests/e2e/test-cases/import-star-from-local-module/output.d.ts
tests/e2e/test-cases/names-collision-across-files/file2.ts
tests/e2e/test-cases/names-collision-across-files/file3.ts
tests/e2e/test-cases/names-collision-across-files/import-star-2.ts
tests/e2e/test-cases/names-collision-across-files/output.d.ts
tests/e2e/test-cases/re-export-in-node_modules/output.d.ts

Fixed handling `import *` statements with local usage but not directly exporting

---

src/bundle-generator.ts
src/types-usage-evaluator.ts
tests/e2e/test-cases/declare-module-and-imports/config.ts
tests/e2e/test-cases/declare-module-and-imports/index.spec.js
tests/e2e/test-cases/declare-module-and-imports/input.d.ts
tests/e2e/test-cases/declare-module-and-imports/output.d.ts

Fixed bug when imported nodes weren't included into bundle if they were used in `declare module` statements only
